In [ ]:
import numpy as np
import pandas as pd

from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [ ]:
# @title 음악 차트 데이터
data_route1 = '/content/gdrive/MyDrive/ROF_gaisum_chart_1823.csv'
music = pd.read_csv(data_route1, encoding='utf-8') #euc-kr
music

             Date  Rank           Title    Artist  Score entertain
0      2018-12-26  88.0       우리 그만 아프자        이현    2.0       하이브
1      2018-12-27  96.0       우리 그만 아프자        이현    1.0       하이브
2      2018-10-28  16.0            IDOL     방탄소년단    9.0       하이브
3      2018-10-28  29.0       FAKE LOVE     방탄소년단    8.0       하이브
4      2018-10-28  32.0        I'm Fine     방탄소년단    7.0       하이브
...           ...   ...             ...       ...    ...       ...
35717  2023-06-30   1.0  퀸카 (Queencard)   (여자)아이들   10.0      큐브엔터
35718  2023-06-30  20.0         Allergy   (여자)아이들    9.0      큐브엔터
35719  2023-06-30  45.0          TOMBOY   (여자)아이들    6.0      큐브엔터
35720  2023-06-30  49.0            Nxde   (여자)아이들    6.0      큐브엔터
35721         NaN   NaN             NaN  LIGHTSUM    NaN      큐브엔터

[35722 rows x 6 columns]

In [ ]:
# @title 주식 데이터
data_route2 = '/content/gdrive/MyDrive/merged_stock.csv'
stock = pd.read_csv(data_route2, encoding='utf-8') #euc-kr
stock

              날짜      종가    전일비      시가      고가      저가      거래량  entertain
0     2023.07.10  22,750    650  23,150  23,400  22,400  226,531       큐브엔터
1     2023.07.07  23,400    250  23,050  23,550  22,800  103,464       큐브엔터
2     2023.07.06  23,150  1,350  24,500  24,700  23,000  300,065       큐브엔터
3     2023.07.05  24,500    300  24,800  24,950  24,100  182,932       큐브엔터
4     2023.07.04  24,800    300  25,100  25,550  24,300  292,454       큐브엔터
...          ...     ...    ...     ...     ...     ...      ...        ...
9875  2016.01.08  42,050    500  41,600  42,350  41,550  117,062  와이지엔터테인먼트
9876  2016.01.07  41,550    750  42,300  42,550  41,450  107,735  와이지엔터테인먼트
9877  2016.01.06  42,300    750  43,000  43,250  42,000   94,564  와이지엔터테인먼트
9878  2016.01.05  43,050    150  42,300  43,600  42,200   79,097  와이지엔터테인먼트
9879  2016.01.04  42,900  1,650  44,450  44,450  42,850   87,676  와이지엔터테인먼트

[9880 rows x 8 columns]

In [ ]:
# @title 뉴스감정 데이터
data_route3 = '/content/gdrive/MyDrive/뉴스감정분석.csv'
news = pd.read_csv(data_route3, encoding='utf-8') #euc-kr
news

,날짜,종목명,제목,감정
0,2020-09-15,에스엠,"공정위, 대금 뺀 불완전 계약서 교부한 SM엔터에 시정명령",-1
1,2020-12-29,에스엠,"버라이어티 500에 방시혁, 이미경, 이수만 등 이름 올려",0
2,2020-12-18,에스엠,보아 “수면제 부작용 심해 日서 졸피뎀 처방” [전문],-1
3,2020-02-20,에스엠,"\n\t\t\tSM엔터테인먼트 ""엑소 멤버 변동 없다...첸 함께하기로""\n\t\t",0
4,2020-01-10,에스엠,[차이나 비즈] SM 이수만 “中오디션 프로 만들겠다”…중국 팬들은 “엑소나 잘 챙겨”,0
...,...,...,...,...
6509,2019-09-10,와이지엔터테이먼트,"\n\t\t\t악동뮤지션, 25일 세 번째 정규앨범 '항해' 공개…쓸쓸한 정취\n\t\t",1
6510,2019-09-06,와이지엔터테이먼트,"\n\t\t\t[엔터브리프] Mnet ‘아이돌학교’ 시청자들, 제작진 고발 등\n\t\t",1
6511,2019-09-06,와이지엔터테이먼트,"조국, '버닝썬' 윤총경 인증샷…""회식 때 찍은 것""",-1
6512,2019-09-03,와이지엔터테이먼트,"비아이 마약·양현석 수사 개입 의혹, 결국 경찰이 수사…""의문 남지 않도록 할 것""",-1
6513,2019-09-02,와이지엔터테이먼트,"패스트트랙 소환 불응 의원…경찰, 檢과 체포영장 협의 중",-1

# 데이터 전처리

In [ ]:
# 날짜와 소속사 기준으로 Score 합
pre_music = music.groupby(['Date', 'entertain']).agg({'Score': ['sum', 'count']}).reset_index()

# 열 이름 변경
pre_music.columns = ['Date', 'entertain', 'ScoreSum', 'ScoreCount']
pre_music

            Date  entertain  ScoreSum  ScoreCount
0     2018-10-28   JYP Ent.       9.0           2
1     2018-10-28        에스엠       9.0           2
2     2018-10-28  와이지엔터테인먼트      14.0           2
3     2018-10-28       큐브엔터      22.0           4
4     2018-10-28        하이브      64.0          13
...          ...        ...       ...         ...
8137  2023-06-30        에스엠      25.0           4
8138  2023-06-30     에프엔씨엔터       4.0           1
8139  2023-06-30  와이지엔터테인먼트      17.0           3
8140  2023-06-30       큐브엔터      34.0           5
8141  2023-06-30        하이브     102.0          16

[8142 rows x 4 columns]

In [ ]:
stock = stock.rename(columns={'날짜': 'Date'})
stock = stock.drop(columns = '전일비')
stock

            Date      종가      시가      고가      저가      거래량  entertain
0     2023.07.10  22,750  23,150  23,400  22,400  226,531       큐브엔터
1     2023.07.07  23,400  23,050  23,550  22,800  103,464       큐브엔터
2     2023.07.06  23,150  24,500  24,700  23,000  300,065       큐브엔터
3     2023.07.05  24,500  24,800  24,950  24,100  182,932       큐브엔터
4     2023.07.04  24,800  25,100  25,550  24,300  292,454       큐브엔터
...          ...     ...     ...     ...     ...      ...        ...
9875  2016.01.08  42,050  41,600  42,350  41,550  117,062  와이지엔터테인먼트
9876  2016.01.07  41,550  42,300  42,550  41,450  107,735  와이지엔터테인먼트
9877  2016.01.06  42,300  43,000  43,250  42,000   94,564  와이지엔터테인먼트
9878  2016.01.05  43,050  42,300  43,600  42,200   79,097  와이지엔터테인먼트
9879  2016.01.04  42,900  44,450  44,450  42,850   87,676  와이지엔터테인먼트

[9880 rows x 7 columns]

In [ ]:
# 날짜 형식 통일
stock['Date'] = stock['Date'].str.replace('.', '-')
print(stock)

            Date      종가      시가      고가      저가      거래량  entertain
0     2023-07-10  22,750  23,150  23,400  22,400  226,531       큐브엔터
1     2023-07-07  23,400  23,050  23,550  22,800  103,464       큐브엔터
2     2023-07-06  23,150  24,500  24,700  23,000  300,065       큐브엔터
3     2023-07-05  24,500  24,800  24,950  24,100  182,932       큐브엔터
4     2023-07-04  24,800  25,100  25,550  24,300  292,454       큐브엔터
...          ...     ...     ...     ...     ...      ...        ...
9875  2016-01-08  42,050  41,600  42,350  41,550  117,062  와이지엔터테인먼트
9876  2016-01-07  41,550  42,300  42,550  41,450  107,735  와이지엔터테인먼트
9877  2016-01-06  42,300  43,000  43,250  42,000   94,564  와이지엔터테인먼트
9878  2016-01-05  43,050  42,300  43,600  42,200   79,097  와이지엔터테인먼트
9879  2016-01-04  42,900  44,450  44,450  42,850   87,676  와이지엔터테인먼트

[9880 rows x 7 columns]

<ipython-input-7-909814efb206>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  stock['Date'] = stock['Date'].str.replace('.', '-')

In [ ]:
# 주식 데이터와 음원차트 데이터 병합
merged_stock = stock.merge(pre_music, on=['Date', 'entertain'], how='left').fillna(0)
merged_stock['Date'] = pd.to_datetime(merged_stock['Date'])
merged_stock

,Date,종가,시가,고가,저가,거래량,entertain,ScoreSum,ScoreCount
0,2023-07-10,"22,750","23,150","23,400","22,400","226,531",큐브엔터,0.0,0.0
1,2023-07-07,"23,400","23,050","23,550","22,800","103,464",큐브엔터,0.0,0.0
2,2023-07-06,"23,150","24,500","24,700","23,000","300,065",큐브엔터,0.0,0.0
3,2023-07-05,"24,500","24,800","24,950","24,100","182,932",큐브엔터,0.0,0.0
4,2023-07-04,"24,800","25,100","25,550","24,300","292,454",큐브엔터,0.0,0.0
...,...,...,...,...,...,...,...,...,...
9875,2016-01-08,"42,050","41,600","42,350","41,550","117,062",와이지엔터테인먼트,0.0,0.0
9876,2016-01-07,"41,550","42,300","42,550","41,450","107,735",와이지엔터테인먼트,0.0,0.0
9877,2016-01-06,"42,300","43,000","43,250","42,000","94,564",와이지엔터테인먼트,0.0,0.0
9878,2016-01-05,"43,050","42,300","43,600","42,200","79,097",와이지엔터테인먼트,0.0,0.0
9879,2016-01-04,"42,900","44,450","44,450","42,850","87,676",와이지엔터테인먼트,0.0,0.0

# 주식+음원차트점수 데이터 csv저장

In [ ]:
# 주식+음원차트점수 데이터
merged_stock.to_csv('/content/gdrive/MyDrive/music_score_stock.csv', index=False)

# 뉴스 제목 감정 추가

In [ ]:
# 기사감정데이터 컬럼명 통합
news = news.drop(columns='제목')
news = news.rename(columns={'날짜': 'Date'})
news = news.rename(columns={'종목명': 'entertain'})
news

            Date  entertain  감정
0     2020-09-15        에스엠  -1
1     2020-12-29        에스엠   0
2     2020-12-18        에스엠  -1
3     2020-02-20        에스엠   0
4     2020-01-10        에스엠   0
...          ...        ...  ..
6509  2019-09-10  와이지엔터테이먼트   1
6510  2019-09-06  와이지엔터테이먼트   1
6511  2019-09-06  와이지엔터테이먼트  -1
6512  2019-09-03  와이지엔터테이먼트  -1
6513  2019-09-02  와이지엔터테이먼트  -1

[6514 rows x 3 columns]

In [ ]:
# 날짜와 소속사 기준으로 기사 감정 합
news['Date'] = pd.to_datetime(news['Date'])
news = news.groupby(['Date', 'entertain'])['감정'].sum().reset_index()
news

           Date  entertain  감정
0    2019-01-01   JYP Ent.   0
1    2019-01-01        에스엠   1
2    2019-01-01  와이지엔터테이먼트  -2
3    2019-01-02   JYP Ent.   0
4    2019-01-02        에스엠  -1
...         ...        ...  ..
3302 2023-06-29        하이브   0
3303 2023-06-30  와이지엔터테이먼트   0
3304 2023-07-13   JYP Ent.   0
3305 2023-07-25   JYP Ent.   1
3306 2023-07-28   JYP Ent.   0

[3307 rows x 3 columns]

In [ ]:
# 기사가 없는 날은 0으로 채워서 병합
fillna_stock = merged_stock.merge(news, on=['Date', 'entertain'], how='left').fillna(0)
fillna_stock

,Date,종가,시가,고가,저가,거래량,entertain,ScoreSum,ScoreCount,감정
0,2023-07-10,"22,750","23,150","23,400","22,400","226,531",큐브엔터,0.0,0.0,0.0
1,2023-07-07,"23,400","23,050","23,550","22,800","103,464",큐브엔터,0.0,0.0,0.0
2,2023-07-06,"23,150","24,500","24,700","23,000","300,065",큐브엔터,0.0,0.0,0.0
3,2023-07-05,"24,500","24,800","24,950","24,100","182,932",큐브엔터,0.0,0.0,0.0
4,2023-07-04,"24,800","25,100","25,550","24,300","292,454",큐브엔터,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
9875,2016-01-08,"42,050","41,600","42,350","41,550","117,062",와이지엔터테인먼트,0.0,0.0,0.0
9876,2016-01-07,"41,550","42,300","42,550","41,450","107,735",와이지엔터테인먼트,0.0,0.0,0.0
9877,2016-01-06,"42,300","43,000","43,250","42,000","94,564",와이지엔터테인먼트,0.0,0.0,0.0
9878,2016-01-05,"43,050","42,300","43,600","42,200","79,097",와이지엔터테인먼트,0.0,0.0,0.0
9879,2016-01-04,"42,900","44,450","44,450","42,850","87,676",와이지엔터테인먼트,0.0,0.0,0.0

# 최종 데이터 저장

In [ ]:
# 최종 데이터
fillna_stock.to_csv('/content/gdrive/MyDrive/music_score_emotion_stock_fillna.csv', index=False)